"""
Refresh data/sha_interventions.csv from the MOH-Kenya OCL terminology server.

    python scripts/fetch_sha_interventions.py

Source: MOH-KENYA / BenefitsAndInterventions on https://ilm-hie.dha.go.ke/ocl,
the catalogue behind the KenyaSocialHealthAuthorityInterventions ValueSet
referenced by the DHA Kenya eClaims FHIR IG.
"""

import csv
import json
import re
import sys
import urllib.request
from datetime import date
from pathlib import Path

OCL = "https://ilm-hie.dha.go.ke/ocl/orgs/MOH-KENYA/sources/BenefitsAndInterventions/concepts/"
OUT = Path(__file__).resolve().parent.parent / "data" / "sha_interventions.csv"
BILLABLE = re.compile(r"^(SHA|PMF)-\d{2}-\d{3}(-SI-\d{3})?$")
PREAUTH_FLAGS = {
    "requires_renal_preauth": "renal",
    "requires_surgical_preauth": "surgical",
    "requires_oncology_preauth": "oncology",
    "requires_radiology_preauth": "radiology",
    "requires_optical_preauth": "optical",
    "needs_manual_preauth_approval": "manual",
    "need_approval_before_claim_submission": "before-submission",
}
# Values not in OCL, kept as clearly labelled samples: code -> (tariff KES, source)
SAMPLE_TARIFFS = {
    "SHA-16-001": ("10650", "https://mycyber.co.ke/sha-for-kidney-dialysis-kenya/ (secondary source; OCL tariff is 0)"),
}


def fetch() -> list[dict]:
    concepts, page = [], 1
    while True:
        req = urllib.request.Request(
            f"{OCL}?limit=500&page={page}&verbose=true", headers={"Accept": "application/json"}
        )
        with urllib.request.urlopen(req, timeout=60) as resp:
            batch = json.load(resp)
        concepts += batch
        if len(batch) < 500:
            return concepts
        page += 1


def tariff(value) -> str:
    # OCL stores 0.0 where no tariff is recorded; treat that as unknown, not free.
    return "" if not value else f"{float(value):g}"


def main() -> int:
    rows = []
    for c in fetch():
        e = c.get("extras") or {}
        if c.get("retired") or not BILLABLE.match(c["id"]) or e.get("active") == "False":
            continue
        rows.append({
            "code": c["id"],
            "description": " ".join(c["display_name"].split()),
            "payment_mechanism": e.get("payment_mechanism") or "",
            "access_point": e.get("access_point") or "",
            "levels": ";".join(sorted(l.replace("LEVEL ", "") for l in e.get("levels_applicable") or [])),
            "gender": e.get("applicable_gender") or "",
            "min_age": e.get("lower_age_limit") or "",
            "max_age": e.get("upper_age_limit") or "",
            **{f"tariff_l{l}": tariff(e.get(f"level_{l}_tariff")) for l in range(2, 7)},
            "preauth": ";".join(v for k, v in PREAUTH_FLAGS.items() if e.get(k) == "True"),
            # Union of both OCL fields: they disagree in places (SHA-16-001 lists QB95,
            # rehabilitation, but its blocks field has QB94, care involving dialysis).
            "diagnoses": ";".join(dict.fromkeys((e.get("diagnosis_lists") or []) + (e.get("diagnosis_blocks") or []))),
            "sample_tariff_kes": SAMPLE_TARIFFS.get(c["id"], ("", ""))[0],
            "sample_tariff_source": SAMPLE_TARIFFS.get(c["id"], ("", ""))[1],
        })
    rows.sort(key=lambda r: r["code"])
    with OUT.open("w", newline="", encoding="utf-8") as fh:
        fh.write(
            f"# SHA benefit interventions. Generated by scripts/fetch_sha_interventions.py on {date.today()}.\n"
            "# Source: MOH-Kenya OCL, MOH-KENYA/BenefitsAndInterventions\n"
            f"#   {OCL}\n"
            "# Active, non-retired billable codes only (SHA-NN-NNN, PMF-NN-NNN, SHA-NN-NNN-SI-NNN).\n"
            "# tariff_l2..l6: OCL level tariffs in KES; blank where OCL records 0 (no tariff set).\n"
            "# sample_tariff_kes: NOT from OCL. A labelled sample, see sample_tariff_source.\n"
        )
        writer = csv.DictWriter(fh, fieldnames=list(rows[0]), lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    print(f"Wrote {len(rows)} interventions to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
